# Generated by Django 2.2.11 on 2020-04-04 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField(default=1)),
                ('store_type', models.CharField(max_length=20)),
                ('shop_no', models.IntegerField(default=1)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
